### ISSUE TITLE
Upgrade to support Gulp 4 and Node 10

### ISSUE THREAD

**Issue by schnaitterm** [UCF/UCF-WordPress-Theme#11]
This theme is not usable on newer versions of Node 10, which breaks `natives@1.1.1`, `graceful-fs@3` (broken because it and `natives` rely on node internals that were changed), and by extension `gulp@3`
see gulpjs/gulp#2162 gulpjs/gulp#2146 and nodejs/node#19786 for more details.

Gulp 4 currently doesn't work with this theme, because the signature of the function `task` has changed. See the error output of `gulp default`: 
```
assert.js:337
    throw err;
    ^

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (site/wp-content/themes/UCF-WordPress-Theme/node_modules/undertaker/lib/set-task.js:10:3)
    at Gulp.task (site/wp-content/themes/UCF-WordPress-Theme/node_modules/undertaker/lib/task.js:13:8)
    at Object.<anonymous> (site/wp-content/themes/UCF-WordPress-Theme/gulpfile.js:53:6)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Liftoff.handleArguments (/usr/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.execute (/usr/lib/node_modules/gulp/node_modules/liftoff/index.js:203:12)
    at module.exports (/usr/lib/node_modules/gulp/node_modules/flagged-respawn/index.js:51:3)
    at Liftoff.<anonymous> (/usr/lib/node_modules/gulp/node_modules/liftoff/index.js:195:5)
    at /usr/lib/node_modules/gulp/node_modules/liftoff/index.js:165:9
    at /usr/lib/node_modules/gulp/node_modules/v8flags/index.js:110:14
```

**Comment by cjg89** [comment]
Packages have been upgraded as of v0.2.2 (see https://github.com/UCF/UCF-WordPress-Theme/pull/13).  If you have any issues running gulp tasks using node 10+ against the latest version of the theme, please let us know.
